defaultPortal: HuloDev
portals:
  - name: HuloDev
    portalId: 25563024
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJaGuPCBMBIJAA0AAAAA4A0DGJCfmAwg8uHNDSju6QwyFMQUlmrULZS0dNBdJSg6zu18DyOKOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhSiU14dCiSRc3BRQBffASeTycdYoEoDZXUxUgBaAA
        expiresAt: '2022-04-12T13:54:36.441Z'
    personalAccessKey: >-
      CiRldTEtZmZkMy0yYTgxLTQ5NjktOGIyYy02YzgxNDJhM2ZhYTUQkJ-YDBjy4c0NKhkABeaRgvvkOLD0yz6HUoncccyE1TaesyzYSgNldTE
