defaultPortal: HuloDev
portals:
  - name: HuloDev
    portalId: 25563024
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CM3Utu6BMBIJAA0AAAAA4A0DGJCfmAwg8uHNDSju6QwyFFLNZUwG0VfA6xTqG4UqOols13TlOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhQ-zKPitqtGR6mciCDsD_JDjkJV50oDZXUxUgBaAA
        expiresAt: '2022-04-12T12:44:19.408Z'
    personalAccessKey: >-
      CiRldTEtZmZkMy0yYTgxLTQ5NjktOGIyYy02YzgxNDJhM2ZhYTUQkJ-YDBjy4c0NKhkABeaRgvvkOLD0yz6HUoncccyE1TaesyzYSgNldTE
