defaultPortal: HuloDev
portals:
  - name: HuloDev
    portalId: 25563024
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLy5gOyBMBIJAA0AAAAA4A0DGJCfmAwg8uHNDSju6QwyFCl-3xD9kbdeIJCWkM3Kpz3oRqMgOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhQ1m9eeYkiUUJZe8vAPlMehU-g1f0oDZXUxUgBaAA
        expiresAt: '2022-04-12T11:19:36.895Z'
    personalAccessKey: >-
      CiRldTEtZmZkMy0yYTgxLTQ5NjktOGIyYy02YzgxNDJhM2ZhYTUQkJ-YDBjy4c0NKhkABeaRgvvkOLD0yz6HUoncccyE1TaesyzYSgNldTE
